### ISSUE TITLE
update script failed..never passed on first run..never

### ISSUE THREAD

**Issue by encryptblockr** [Jarli01/xenorchestra_updater#26]
I have never ran this update script and have it pass first try..never 
will be great to have something that has a better success rate

```
[/opt/xen-orchestra/packages/xo-cli/src/index.js] Added following polyfills:
  es6.promise { "node":"6" }
  es6.array.sort { "node":"6" }
  web.dom.iterable { "node":"6" }
  es6.symbol { "node":"6" }
  es7.symbol.async-iterator { "node":"6" }
Successfully compiled 3 files with Babel.
Successfully compiled 4 files with Babel.
Successfully compiled 8 files with Babel.
Successfully compiled 2 files with Babel.
Successfully compiled 9 files with Babel.
Successfully compiled 9 files with Babel.
Successfully compiled 3 files with Babel.
Successfully compiled 5 files with Babel.
Successfully compiled 22 files with Babel.
[14:21:10] Using gulpfile /opt/xen-orchestra/packages/xo-web/gulpfile.js
[14:21:10] Starting 'clean'...
[14:21:10] Finished 'clean' after 43 ms
index generated src/common/themes/index.js
index generated src/common/intl/locales/index.js
* xo-web:build − NODE_ENV=production gulp build
[14:21:11] Using gulpfile /opt/xen-orchestra/packages/xo-web/gulpfile.js
[14:21:11] Starting 'build'...
[14:21:11] Starting 'buildPages'...
[14:21:11] Starting 'buildScripts'...
[14:21:11] Starting 'buildStyles'...
[14:21:11] Starting 'copyAssets'...
[14:21:19] Finished 'buildPages' after 8.43 s
[14:21:19] Finished 'copyAssets' after 8.48 s
DEPRECATION WARNING on line 29, column 8 of /opt/xen-orchestra/packages/xo-web/src/index.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 63, column 8 of /opt/xen-orchestra/packages/xo-web/src/index.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
[14:21:27] Finished 'buildStyles' after 16 s
[14:22:13] 'buildScripts' errored after 1.03 min
[14:22:13] Error: Cannot find module 'reaclette' from '/opt/xen-orchestra/packages/xo-web/src/xo-app/xoa/update'
    at /opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /opt/xen-orchestra/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
[14:22:13] 'build' errored after 1.03 min
* xo-web:build − Error: 1
✖ 6
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Updated version 5.46.0 / 5.46.0
Checking plugins...
Creating link for xo-server-sdn-controller
Creating link for xo-server-test
Restarting xo-server...
```

will keep working to fix and will update this

**Comment by Jarli01** [comment]
Please provide answers as to the New Issue template or I'll be forced to close this issue.

**Comment by encryptblockr** [comment]
ran the install script instead and it worked and updated installation
this update script needs work..it never worked
i usually have to remove current installation and install brand new
or in this case just run the install script on top and it worked

thanks
