### ISSUE TITLE
xoa not working after update with cli

### ISSUE THREAD

**Issue by BerT666** [Jarli01/xenorchestra_updater#34]
**Describe the bug**
After updating (  curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -f ) the WebGUI does not load. tried to do this several times within the last week.

**To Reproduce**
1. update using " curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -f"
2. restart server
3. try to access the WebGUI Page => site not found
4. regarding netstat, the Webserver does not start at all

**Expected behavior**
The Login Page should be accessible after updating

**Desktop/Server details (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Browser [tested with Chrome, Firefox and Edge; each with latest patch level]

**Confirm XOCE services are running**
```
root@xoa:/home/tb# systemctl status xo-server.service
● xo-server.service - XO Server
   Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Tue 2020-05-26 08:41:52 UTC; 8s ago
  Process: 19909 ExecStart=/usr/local/bin/node ./bin/xo-server (code=exited, status=0/SUCCESS)
 Main PID: 19909 (code=exited, status=0/SUCCESS)

Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Mai 26 08:41:52 xoa systemd[1]: Stopped XO Server.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Start request repeated too quickly.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Failed with result 'start-limit-hit'.
Mai 26 08:41:52 xoa systemd[1]: Failed to start XO Server.

**Provide the output of journalctl logs**
-- Logs begin at Sun 2020-03-15 21:36:31 UTC. --
Mai 26 08:41:51 xoa xo-server[19874]:     at Module._compile (module.js:653:30)
Mai 26 08:41:51 xoa xo-server[19874]:     at Object.Module._extensions..js (module.js:664:10)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module.load (module.js:566:32)
Mai 26 08:41:51 xoa xo-server[19874]:     at tryModuleLoad (module.js:506:12)
Mai 26 08:41:51 xoa xo-server[19874]:     at Function.Module._load (module.js:498:3)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module.require (module.js:597:17)
Mai 26 08:41:51 xoa xo-server[19874]:     at require (internal/module.js:11:18)
Mai 26 08:41:51 xoa xo-server[19874]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo-mixins/index.js:35:1)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module._compile (module.js:653:30)
Mai 26 08:41:51 xoa xo-server[19874]:     at Object.Module._extensions..js (module.js:664:10)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module.load (module.js:566:32)
Mai 26 08:41:51 xoa xo-server[19874]:     at tryModuleLoad (module.js:506:12)
Mai 26 08:41:51 xoa xo-server[19874]:     at Function.Module._load (module.js:498:3)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module.require (module.js:597:17)
Mai 26 08:41:51 xoa xo-server[19874]:     at require (internal/module.js:11:18)
Mai 26 08:41:51 xoa xo-server[19874]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo.js:17:1)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module._compile (module.js:653:30) code: 'MODULE_NOT_FOUND' } }
Mai 26 08:41:51 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Mai 26 08:41:51 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 4.
Mai 26 08:41:51 xoa systemd[1]: Stopped XO Server.
Mai 26 08:41:51 xoa systemd[1]: Started XO Server.
Mai 26 08:41:52 xoa xo-server[19909]: 2020-05-26T08:41:52.352Z xo:xo-server ERROR uncaught exception { error: { Error: Cannot find module 'openpgp'
Mai 26 08:41:52 xoa xo-server[19909]:     at Function.Module._resolveFilename (module.js:548:15)
Mai 26 08:41:52 xoa xo-server[19909]:     at Function.Module._load (module.js:475:25)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.require (module.js:597:17)
Mai 26 08:41:52 xoa xo-server[19909]:     at require (internal/module.js:11:18)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo-mixins/config-management.js:1:1)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module._compile (module.js:653:30)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.Module._extensions..js (module.js:664:10)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.load (module.js:566:32)
Mai 26 08:41:52 xoa xo-server[19909]:     at tryModuleLoad (module.js:506:12)
Mai 26 08:41:52 xoa xo-server[19909]:     at Function.Module._load (module.js:498:3)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.require (module.js:597:17)
Mai 26 08:41:52 xoa xo-server[19909]:     at require (internal/module.js:11:18)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo-mixins/index.js:35:1)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module._compile (module.js:653:30)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.Module._extensions..js (module.js:664:10)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.load (module.js:566:32)
Mai 26 08:41:52 xoa xo-server[19909]:     at tryModuleLoad (module.js:506:12)
Mai 26 08:41:52 xoa xo-server[19909]:     at Function.Module._load (module.js:498:3)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.require (module.js:597:17)
Mai 26 08:41:52 xoa xo-server[19909]:     at require (internal/module.js:11:18)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo.js:17:1)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module._compile (module.js:653:30) code: 'MODULE_NOT_FOUND' } }
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Mai 26 08:41:52 xoa systemd[1]: Stopped XO Server.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Start request repeated too quickly.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Failed with result 'start-limit-hit'.
Mai 26 08:41:52 xoa systemd[1]: Failed to start XO Server.
```
**Provide answers to these questions:**
* Is is an upgrade?
* Version of XOCE server and web interface you're running: 5.59.0
* What OS is XOCE running on? : Ubuntu 18.04 LTS (latest patches installed)
* What method did you use to install XOCE: xo_install.sh
* What specific XOCE page you're on, and what specific element you're interacting with to trigger the error: LoginPage

* Indicate whether or not you've manually edited any data directly. : Not edited any data

**Comment by Danp2** [comment]
Looks like you are missing a package (openpgp). Did you encounter any errors during the upgrade process?

You can try to issue the following commands from the `\opt\xen-orchestra` directory --
```
rm -rf node_modules
yarn
yarn build
```

Then post the resulting output here. Be sure to wrap it in triple tick marks (```) so that it is easier to read.

**Comment by ingohz** [comment]
Same here with Debian 10.4. After an update yesterday I get this error at startup
```xo-server[72572]: 2020-05-28T09:37:28.111Z xo:xo-server ERROR uncaught exception { error: { Error: Cannot find module 'openpgp'```

Here is the output of ```yarn``` and ```yarn build```. Until last week everything worked fine... :

```
root@xoa:/opt/xen-orchestra# yarn
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error xo-server-auth-ldap@0.7.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.16.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@xoa:/opt/xen-orchestra# yarn build
yarn run v1.22.4
$ scripts/run-script --parallel build
module.js:550
    throw err;
    ^

Error: Cannot find module 'promise-toolbox'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/xen-orchestra/scripts/run-script:4:32)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@xoa:/opt/xen-orchestra# 
```

**Comment by Danp2** [comment]
@ingohz It appears that you are using an older version of Node. Please rerun the update with the following and let us know if this fixes the issue --
```
sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -n
```

**Comment by ingohz** [comment]
Took a while, but it's working again now. I did the node update first:
```sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -n stable```
and then forced a rebuild:
```curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -f```
I got this error message and therefore increased the RAM. Not so easy without xoa and wincenter ;)
```FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory```

After a reboot all runs fine now. Thank you very much for your help!

**Comment by Danp2** [comment]
@BerT666 It's possible that you are also being affected by an out of date version of node. What does `node -v` return?

**Comment by BerT666** [comment]
node -v
v8.16.2

**Comment by Danp2** [comment]
@BerT666 Please run the following command, which should update node and then rebuild the system --
```
sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -n
```

**Comment by BerT666** [comment]
@Danp2 : sawyour post too late...

I did it as ingohz described and now it works again.

Thanks a lot
