### ISSUE TITLE
Plugin transport-email (v0.6.0) not working

### ISSUE THREAD

**Issue by gskger** [Jarli01/xenorchestra_updater#39]
#### Expected Behavior

transport-email plugin can be activated under settings/plugins and sends emails (in combinatin with the backup-report plugin). The plugin was working for a long time before the update and hence is configured correctly.

-----

#### Actual Behavior

transport-email plugin (v0.6.0) is inactive after running xenorchestra_updater. Activating it in the plugin list results in a <plugin not configured> error. Open the configuration view, all previous settings are shown as expected. When trying to save a minor change, another error ist shown <strict mode: unknown keyword: "enumNames">.

-----

#### Confirm XOCE services are running

``` 
systemctl status xo-server.service
● xo-server.service - XO Server
   Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset
   Active: active (running) since Mon 2021-04-05 11:07:09 CEST; 9min ago
 Main PID: 63968 (node)
    Tasks: 12 (limit: 9830)
   CGroup: /system.slice/xo-server.service
           └─63968 /usr/local/bin/node ./bin/xo-server

Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.212Z xo:plu
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.216Z xo:plu
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.270Z xo:plu
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.273Z xo:xo-
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.370Z xo:plu
Apr 05 11:08:11 e2052.2drs.net xo-server[63968]: 2021-04-05T09:08:11.162Z xo:mai
Apr 05 11:08:28 e2052.2drs.net xo-server[63968]: 2021-04-05T09:08:28.145Z xo:api
Apr 05 11:08:37 e2052.2drs.net xo-server[63968]: 2021-04-05T09:08:37.730Z xo:api
Apr 05 11:13:04 e2052.2drs.net xo-server[63968]: 2021-04-05T09:13:04.613Z xo:api
Apr 05 11:16:12 e2052.2drs.net xo-server[63968]: 2021-04-05T09:16:12.610Z xo:api
```

#### Provide the output of journalctl logs

```
journalctl -u xo-server -f -n 50
-- Logs begin at Wed 2021-03-24 19:10:01 CET. --
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at subschemaCode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:125:7)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at KeywordCxt.subschema (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:487:5)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at applyPropertySchema (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:45:11)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at Object.code (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:32:9)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at keywordCode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:519:9)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at /opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:265:9
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: }
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.211Z xo:plugin INFO successfully register perf-alert
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.211Z xo:plugin INFO successfully register test-plugin
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.211Z xo:plugin INFO failed register transport-email
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.211Z xo:plugin INFO strict mode: unknown keyword: "enumNames" {
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:   error: Error: strict mode: unknown keyword: "enumNames"
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at checkStrictMode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/util.ts:211:28)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at checkUnknownRules (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/util.ts:27:22)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at Object.alwaysValidSchema (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/util.ts:17:3)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at /opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:23:48
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at Array.filter (<anonymous>)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at Object.code (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:23:33)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at keywordCode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:519:9)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at /opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:265:9
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at CodeGen.code (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/codegen/index.ts:525:33)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at CodeGen.block (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/codegen/index.ts:680:20)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at iterateKeywords (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:262:7)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at groupKeywords (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:241:7)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at /opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:233:38
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at CodeGen.code (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/codegen/index.ts:525:33)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at CodeGen.block (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/codegen/index.ts:680:20)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at schemaKeywords (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:232:7)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at typeAndKeywords (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:162:3)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at subSchemaObjCode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:148:3)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at subschemaCode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:125:7)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at KeywordCxt.subschema (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:487:5)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at applyPropertySchema (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:45:11)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]:       at Object.code (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:32:9)
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: }
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.212Z xo:plugin INFO successfully register transport-icinga2
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.212Z xo:plugin INFO successfully register transport-nagios
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.212Z xo:plugin INFO successfully register transport-slack
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.212Z xo:plugin INFO successfully register transport-xmpp
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.212Z xo:plugin INFO successfully register web-hooks
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.212Z xo:plugin INFO successfully register backup-reports
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.216Z xo:plugin INFO successfully register audit
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.270Z xo:plugin INFO successfully register usage-report
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.273Z xo:xo-server:sdn-controller:tls-connect DEBUG Certificates have been updated
Apr 05 11:07:14 e2052.2drs.net xo-server[63968]: 2021-04-05T09:07:14.370Z xo:plugin INFO successfully register sdn-controller
Apr 05 11:08:11 e2052.2drs.net xo-server[63968]: 2021-04-05T09:08:11.162Z xo:main INFO + WebSocket connection (::ffff:192.168.10.11)
Apr 05 11:08:28 e2052.2drs.net xo-server[63968]: 2021-04-05T09:08:28.145Z xo:api WARN admin | plugin.load(...) [30ms] =!> XoError: plugin not configured
Apr 05 11:08:37 e2052.2drs.net xo-server[63968]: 2021-04-05T09:08:37.730Z xo:api WARN admin | plugin.configure(...) [13ms] =!> Error: strict mode: unknown keyword: "enumNames"
Apr 05 11:13:04 e2052.2drs.net xo-server[63968]: 2021-04-05T09:13:04.613Z xo:api WARN admin | plugin.load(...) [9ms] =!> XoError: plugin not configured
Apr 05 11:16:12 e2052.2drs.net xo-server[63968]: 2021-04-05T09:16:12.610Z xo:api WARN admin | plugin.configure(...) [21ms] =!> Error: strict mode: unknown keyword: "enumNames"
```
 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? > an upgrade.
- Version of XOCE server and web interface you're running. > xo-server 5.78.2, xo-web 5.80.0
- What OS is XOCE running on? > Debian 10
- What method you used to install XOCE (xo_install.sh, manual installation, etc) > xo_install.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error > settings/plugin
- If a stacktrace is provided in the error, include that too. > ?
- Any errors that appear in your browser's error console. > none
- Include what you've done so far in the installation, and if you got any error messages along the way. > none
- Indicate whether or not you've manually edited any data directly. > did not edit data

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Jarli01** [comment]
Plugins aren't anything we do "something" with, we just install them for you. 

With that, have you tested with a new install and see if this issue occurs? 

In the logs provided I see a few issues of "plugins not configured", can you attempt entering the configuration details again for the corresponding plugins and report back?

**Comment by gskger** [comment]
Did a fresh XO from source install (```curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh | bash```) on a new Debian 10 VM fully updated.
The issue occurs as well as described above when trying to activate the plugin:
```
plugin.load
{
  "id": "transport-email"
}
{
  "code": 10,
  "data": {},
  "message": "plugin not configured",
  "name": "XoError",
  "stack": "XoError: plugin not configured
    at factory (/opt/xen-orchestra/packages/xo-common/src/api-errors.js:21:32)
    at _default.loadPlugin (/opt/xen-orchestra/packages/xo-server/src/xo-mixins/plugins.js:191:13)
    at Object.loadPlugin (/opt/xen-orchestra/node_modules/lodash/_createBind.js:23:15)
    at Object.call (/opt/xen-orchestra/packages/xo-server/src/api/plugin.js:61:14)
    at Api.callApiMethod (/opt/xen-orchestra/packages/xo-server/src/xo-mixins/api.js:304:33)"
} 
```
When I configure the (still inactive) plugin with the settings that worked for a long time, the configuration can not be saved:
```
plugin.configure
{
  "id": "transport-email",
  "configuration": {
    "from": {
      "name": "XXXXX",
      "address": "XXXXX"
    },
    "transport": {
      "host": "XXXXX",
      "port": 465,
      "secure": true,
      "user": "XXXXX",
      "password": "* obfuscated *"
    }
  }
}
{
  "message": "strict mode: unknown keyword: \"enumNames\"",
  "name": "Error",
  "stack": "Error: strict mode: unknown keyword: \"enumNames\"
    at checkStrictMode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/util.ts:211:28)
    at checkUnknownRules (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/util.ts:27:22)
    at Object.alwaysValidSchema (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/util.ts:17:3)
    at /opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:23:48
    at Array.filter (<anonymous>)
    at Object.code (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:23:33)
    at keywordCode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:519:9)
    at /opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:265:9
    at CodeGen.code (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/codegen/index.ts:525:33)
    at CodeGen.block (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/codegen/index.ts:680:20)
    at iterateKeywords (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:262:7)
    at groupKeywords (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:241:7)
    at /opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:233:38
    at CodeGen.code (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/codegen/index.ts:525:33)
    at CodeGen.block (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/codegen/index.ts:680:20)
    at schemaKeywords (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:232:7)
    at typeAndKeywords (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:162:3)
    at subSchemaObjCode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:148:3)
    at subschemaCode (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:125:7)
    at KeywordCxt.subschema (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/compile/validate/index.ts:487:5)
    at applyPropertySchema (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:45:11)
    at Object.code (/opt/xen-orchestra/packages/xo-server/node_modules/ajv/lib/vocabularies/applicator/properties.ts:32:9)"
} 
```
Maybe an upstream (Vates team) issue? There is an [active thread on the XCP-ng forum](https://xcp-ng.org/forum/topic/4439/plugin-transport-email-v0-6-0-broken)

**Comment by Jarli01** [comment]
Very likely a bug in the upstream then, please open a case on their [GH](https://github.com/vatesfr) as well as forums.

I'm sure they'll be able to assist with getting the issue fixed.

**Comment by Jarli01** [comment]
P.S Olivier will be thornery no matter what about any issues that aren't specifically from XOA or XO from Source. 

I ran an install here from source and am seeing the same issue.
