### ISSUE TITLE
Updater and Installer Scrripts Terminate Abnormally

### ISSUE THREAD

**Issue by sonoracomm** [Jarli01/xenorchestra_updater#60]
#### Expected Behavior

Updater and installer scripts to complete without error

Suspect upstream issue

-----

#### Actual Behavior

This is the final update command I used:

`curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -f -n stable`

Both scripts terminate abnormally with the same/similar errors - this error is from fresh install - running update, service is restarted

```
<snip>
Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
[09:38:31] Finished 'copyAssets' after 59 s
src/views/settings/SettingsView.vue:102:17 - error TS2304: Cannot find name 'XO_LITE_VERSION'.

102 const version = XO_LITE_VERSION;
                    ~~~~~~~~~~~~~~~

src/views/settings/SettingsView.vue:103:17 - error TS2304: Cannot find name 'XO_LITE_GIT_HEAD'.

103 const gitHead = XO_LITE_GIT_HEAD;
                    ~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/views/settings/SettingsView.vue:102

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "type-check" exited with 2.
* @xen-orchestra/lite:build − Error: 1
[09:40:11] Finished 'buildScripts' after 2.65 min
[09:40:11] Finished 'build' after 2.65 min
✖ 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@va-xoce:~#
```

-----

#### Confirm XOCE services are running

With update script, services do restart

#### Provide the output of journalctl logs

I don't know how accurate/useful this is due to restored snapshot

```
journalctl -u xo-server -f -n 50
-- Logs begin at Sun 2019-11-03 00:22:05 MST. --
Nov 03 09:45:49 ubuntu xo-server[674]:   error: Error: Cannot find module '/usr/local/lib/node_modules/xo-server-cloud'
Nov 03 09:45:49 ubuntu xo-server[674]:   Require stack:
Nov 03 09:45:49 ubuntu xo-server[674]:   - /opt/xen-orchestra/packages/xo-server/dist/index.mjs
Nov 03 09:45:49 ubuntu xo-server[674]:       at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
Nov 03 09:45:49 ubuntu xo-server[674]:       at requireResolve (node:internal/modules/cjs/helpers:108:19)
Nov 03 09:45:49 ubuntu xo-server[674]:       at Xo.call (file:///opt/xen-orchestra/packages/xo-server/src/index.mjs:306:32)
Nov 03 09:45:49 ubuntu xo-server[674]:       at Xo.call (file:///opt/xen-orchestra/packages/xo-server/src/index.mjs:353:25)
Nov 03 09:45:49 ubuntu xo-server[674]:       at Array.<anonymous> (file:///opt/xen-orchestra/packages/xo-server/src/index.mjs:374:36)
Nov 03 09:45:49 ubuntu xo-server[674]:       at Function.from (<anonymous>)
Nov 03 09:45:49 ubuntu xo-server[674]:       at asyncMap (/opt/xen-orchestra/@xen-orchestra/async-map/index.js:23:28)
Nov 03 09:45:49 ubuntu xo-server[674]:       at Xo.registerPluginsInPath (file:///opt/xen-orchestra/packages/xo-server/src/index.mjs:372:9)
Nov 03 09:45:49 ubuntu xo-server[674]:       at runMicrotasks (<anonymous>)
Nov 03 09:45:49 ubuntu xo-server[674]:       at processTicksAndRejections (node:internal/process/task_queues:96:5)
Nov 03 09:45:49 ubuntu xo-server[674]:       at runNextTicks (node:internal/process/task_queues:65:3)
Nov 03 09:45:49 ubuntu xo-server[674]:       at processImmediate (node:internal/timers:437:9)
Nov 03 09:45:49 ubuntu xo-server[674]:       at process.callbackTrampoline (node:internal/async_hooks:130:17) {
Nov 03 09:45:49 ubuntu xo-server[674]:     code: 'MODULE_NOT_FOUND',
Nov 03 09:45:49 ubuntu xo-server[674]:     requireStack: [ '/opt/xen-orchestra/packages/xo-server/dist/index.mjs' ]
Nov 03 09:45:49 ubuntu xo-server[674]:   }
Nov 03 09:45:49 ubuntu xo-server[674]: }
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.149Z xo:plugin INFO successfully register auth-github
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register auth-google
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register auth-ldap
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register auth-saml
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register netbox
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register test-plugin
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register transport-icinga2
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register transport-nagios
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register transport-slack
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register transport-xmpp
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register web-hooks
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register backup-reports
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.150Z xo:plugin INFO successfully register transport-email
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.173Z xo:plugin INFO successfully register audit
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.173Z xo:plugin INFO successfully register load-balancer
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.173Z xo:plugin INFO successfully register perf-alert
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.218Z xo:plugin INFO successfully register usage-report
Nov 03 09:45:51 ubuntu xo-server[674]: 2022-11-03T16:45:51.271Z xo:plugin INFO successfully register sdn-controller
Nov 03 09:48:47 ubuntu xo-server[674]: 2022-11-03T16:48:47.202Z xo:xo-mixins:backups-ng WARN listVmBackups for remote f5349f17-1829-4312-a34f-c7f24eb8fc2b: {
Nov 03 09:48:47 ubuntu xo-server[674]:   error: TypeError: Cannot read properties of undefined (reading 'name_description')
Nov 03 09:48:47 ubuntu xo-server[674]:       at formatVmBackup (/opt/xen-orchestra/@xen-orchestra/backups/formatVmBackups.js:27:35)
Nov 03 09:48:47 ubuntu xo-server[674]:       at Array.map (<anonymous>)
Nov 03 09:48:47 ubuntu xo-server[674]:       at /opt/xen-orchestra/@xen-orchestra/backups/formatVmBackups.js:35:52
Nov 03 09:48:47 ubuntu xo-server[674]:       at /opt/xen-orchestra/node_modules/lodash/mapValues.js:38:34
Nov 03 09:48:47 ubuntu xo-server[674]:       at /opt/xen-orchestra/node_modules/lodash/_createBaseFor.js:17:11
Nov 03 09:48:47 ubuntu xo-server[674]:       at baseForOwn (/opt/xen-orchestra/node_modules/lodash/_baseForOwn.js:13:20)
Nov 03 09:48:47 ubuntu xo-server[674]:       at mapValues (/opt/xen-orchestra/node_modules/lodash/mapValues.js:37:3)
Nov 03 09:48:47 ubuntu xo-server[674]:       at formatVmBackups (/opt/xen-orchestra/@xen-orchestra/backups/formatVmBackups.js:35:10)
Nov 03 09:48:47 ubuntu xo-server[674]:       at Function.<anonymous> (file:///opt/xen-orchestra/packages/xo-server/src/xo-mixins/backups-ng/index.mjs:537:11)
Nov 03 09:48:47 ubuntu xo-server[674]: }
```

#### What version of Node are you running?

This may change during forced rebuild...

v16.17.1
 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?   Tried both
- Version of XOCE server and web interface you're running  Latest the updater and installer scripts install
- What OS is XOCE running on?  Ubuntu 20.04 (update) and 22.04 (fresh install)
- What method you used to install XOCE (xo_install.sh, manual installation, etc)  Your install script
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error Just running either script as I have done many times
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.  After update failure, no backups show in Restore
- Include what you've done so far in the installation, and if you got any error messages along the way.  Tried update and fresh install
- Indicate whether or not you've manually edited any data directly.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Danp2** [comment]
> What version of Node are you running?  v16.17.1

Can you check it after the script runs? It should be v18.12.0, which is the current LTS release. It's possible that the `-n` option isn't working correctly. FWIW, I usually update node separately using the command `n lts`.

**Comment by sonoracomm** [comment]
Thank you very much for your comment!

Still the same errors.

Here's what I did:

Updating Ubuntu 20.04:

`n lts`

(updated to v18.12.0)

`apt update && apt -y dist-upgrade && apt -y autoremove && apt clean && reboot
`
```
systemctl status xo-server.service
● xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-11-03 11:10:03 MST; 41s ago
   Main PID: 668 (node)
      Tasks: 11 (limit: 3452)
     Memory: 270.2M
     CGroup: /system.slice/xo-server.service
             └─668 /usr/local/bin/node ./dist/cli.mjs

Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.169Z xo:plugin INFO successfully register transport-nagios
Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.169Z xo:plugin INFO successfully register transport-xmpp
Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.169Z xo:plugin INFO successfully register web-hooks
Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.169Z xo:plugin INFO successfully register backup-reports
Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.169Z xo:plugin INFO successfully register transport-email
Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.191Z xo:plugin INFO successfully register audit
Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.191Z xo:plugin INFO successfully register load-balancer
Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.191Z xo:plugin INFO successfully register perf-alert
Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.251Z xo:plugin INFO successfully register usage-report
Nov 03 11:10:17 ubuntu xo-server[668]: 2022-11-03T18:10:17.336Z xo:plugin INFO successfully register sdn-controller
```

`curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -f`

```
<snip>
Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
[11:16:06] Finished 'copyAssets' after 1.05 min
src/views/settings/SettingsView.vue:102:17 - error TS2304: Cannot find name 'XO_LITE_VERSION'.

102 const version = XO_LITE_VERSION;
                    ~~~~~~~~~~~~~~~

src/views/settings/SettingsView.vue:103:17 - error TS2304: Cannot find name 'XO_LITE_GIT_HEAD'.

103 const gitHead = XO_LITE_GIT_HEAD;
                    ~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/views/settings/SettingsView.vue:102

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "type-check" exited with 2.
* @xen-orchestra/lite:build − Error: 1
[11:17:44] Finished 'buildScripts' after 2.7 min
[11:17:44] Finished 'build' after 2.7 min
✖ 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Updated version 5.105.0 / 5.106.0
Updated commit ccafc15b669cf71ab1ec68cdc81d887bc829b2b2 2022-11-03 14:52:01 +0100
Checking plugins...
Ignoring xo-server-test plugin
Cleanup plugins...
Restarting xo-server...

```

After that, XOCE still seems to be working.

I did not try the installer script again, but I can if you need me to.

Thanks,

G

**Comment by Danp2** [comment]
Pretty confident that this issue is due to the upstream commits made earlier today. I see this earlier in the build process --

```
* xo-web:build − GIT_HEAD=$(git rev-parse HEAD) NODE_ENV=production gulp build
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
transforming (1) index.htmlERROR: "type-check" exited with 137.
* @xen-orchestra/lite:build − Error: 1
 ```

Then I get this --

```
Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
Killed
* xo-import-servers-csv:build − Error: 137
```

And lastly I get this --

```

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
[13:35:31] Finished 'copyAssets' after 3.82 min
[13:37:10] Finished 'buildScripts' after 5.47 min
[13:37:10] Finished 'build' after 5.47 min
✖ 2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I imagine that this will be fixed pretty quickly. In the mean time, it should build correctly if you checkout commit `0623d837c1e7aff90cde2c546ade6a8e507b6700`.

**Comment by Danp2** [comment]
It seems that their internal build process fails with the same errors -- https://github.com/vatesfr/xen-orchestra/actions/runs/3386267269/jobs/5625446758#step:4:1175

**Comment by Danp2** [comment]
Looks like the issue has been fixed upstream.  Can you retest?

**Comment by Danp2** [comment]
> The installer script still had the same errors.

I don't see how that is possible. 🤔

**Comment by Danp2** [comment]
@sonoracomm Those instructions were changed earlier today, so that may explain why your earlier attempt failed. However, you shouldn't have encountered the issues with `XO_LITE` once that issue was fixed in the source code.

Glad your most recent install ran without issues. 👍
